---
- name: CMDB Mac Setup Playbook
  hosts: localhost
  connection: local

  vars:
    - downloads: ~/.ansible-downloads/

  tasks:
    - name: Create Ansible downloads directory
      file: path={{downloads}} state=directory
    - import_tasks: preferences/softwareupdate.yml
    - import_tasks: preferences/dotfiles.yml
    # - import_tasks: preferences/preferences.yml

- import_playbook: apps/homebrew.yml

- import_playbook: homebrew_packages.yml

- import playbook: conda_packages.yml

- name: Run setup scripts
  - hosts: all
    connection: local
  tasks:
    - name: Run conda setup
      shell: install_conda_packages.sh
      args:
        executable: /bin/bash

    - name: Fetch data
      shell: get_data.sh
      args:
        executable: /bin/bash