---
# Sublime Text.
# Note: Currently, to complete installation, you have to manually install. Also creates does not like path with spaces.
# Package Control; see: https://sublime.wbond.net/installation.
- hosts: all
  connection: local
  gather_facts: False
  vars:
    app_name: Sublime\ Text\ 2
    app_name_pretty: "Sublime Text"
    app_url: "http://c758482.r82.cf2.rackcdn.com/Sublime%20Text%202.0.2.dmg"
    installer_type: app
    install_method: dmg
    mount_path: /Volumes/{{app_name}}/
    downloads: ~/.ansible-downloads/
    creates: /usr/bin/subl

  tasks:
    - include: ../install/{{install_method}}.yml

    - name: Create symlink subl for Sublime Text's subl command
      file: src=/Applications/Sublime\ Text\ 2.app/Contents/SharedSupport/bin/subl dest=/usr/bin/subl state=link
      sudo: true

    - name: Create symlink sublime for Sublime Text's subl command
      file: src=/Applications/Sublime\ Text\ 2.app/Contents/SharedSupport/bin/subl dest=/usr/bin/sublime state=link
      sudo: true

    - name: Copy Sublime settings files.
      copy: "src='../templates/sublime/{{ item }}' dest='~/Library/Application\ Support/Sublime\ Text\ 2/Packages/User/{{ item }}'"
      sudo: no
      with_items:
      - "Default (OSX).sublime-keymap"
      - "Package Control.sublime-settings"
      - "Preferences.sublime-settings"
    # - name: "Copy settings (example, don't use)."
    #   shell: cp -r init/Preferences.sublime-settings ~/Library/Application\ Support/Sublime\ Text*/Packages/User/Preferences.sublime-settings 2> /dev/null
